import Head from 'next/head'
import Boost from '../components/Boost'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import LinkSection from '../components/LinkSection'
import Statistics from '../components/Statistics'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Shortly App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <Header />
            <Hero />
            <LinkSection />
            <Statistics />
            <Boost />
            <Footer />
        </div>
    )
}
